# Generated by Django 4.0.4 on 2022-04-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('prob_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prob_name', models.CharField(max_length=100)),
                ('prob_link', models.CharField(max_length=100)),
                ('test_input', models.CharField(max_length=100)),
                ('test_output', models.CharField(max_length=100)),
                
            ],
        ),
    ]
