# Generated by Django 4.0.4 on 2022-04-13 06:45

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='prob_link',
            field=models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/gs24/Files/Problem1')),
        ),
    ]
