# Generated by Django 4.0.4 on 2022-04-17 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enroll', '0003_alter_problem_prob_link_alter_problem_test_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='prob_link',
            field=models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/gs24/static')),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('sol_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_input', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/gs24/TEST-INPUT'))),
                ('test_output', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/gs24/TEST-OUTPUT'))),
                ('user_id', models.IntegerField()),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enroll.problem')),
                ('sol_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
