# Generated by Django 4.0.4 on 2022-04-19 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('prob_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prob_name', models.CharField(max_length=100)),
                ('prob_link', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/Hello/static'))),
                ('test_input', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/Hello/TEST-INPUT'))),
                ('test_output', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/Hello/TEST-OUTPUT'))),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('sol_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_input', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/Hello/TEST-INPUT'))),
                ('test_output', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/91917/new-django-project/Hello/TEST-OUTPUT'))),
                ('user_id', models.IntegerField()),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.problem')),
                ('sol_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
