# Generated by Django 4.0.4 on 2022-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('vis_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vis_name', models.CharField(max_length=100)),
                ('vis_email', models.CharField(max_length=100)),
                ('vis_password', models.CharField(max_length=100)),
                ('vis_problem_attempted', models.IntegerField()),
                ('vis_problem_solved', models.IntegerField()),
                ('vis_problem_list', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='user_id',
            new_name='vis_id',
        ),
        migrations.AddField(
            model_name='problem',
            name='editorial',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
